### PR TITLE
implements testFailureIgnore to be able to not fail the build but make it unstable

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: olivier lamy <olamy@apache.org>

### CODE REVIEW

**Comment by normanmaurer** [comment]
@olamy thanks a lot... just let me know if you would also have a new release with this included and I will make it happen :)

**Comment by olamy** [comment]
@normanmaurer thanks for merging so quickly. Sure for the release if you have a bit of time I will definitely appreciate :)

**Comment by normanmaurer** [comment]
@olamy done https://search.maven.org/artifact/me.normanmaurer.maven.autobahntestsuite/autobahntestsuite-maven-plugin/0.1.6/maven-plugin

**Comment by olamy** [comment]
@normanmaurer Thanks mate!

**Pull request merged**
